### ISSUE TITLE
S3 mounted files not syncing when burst job ends in ver. 0.2.16

### ISSUE THREAD

**Issue by cyrus** [burstable-ai/burst#111]
I just upgraded from 0.2.13 to 0.2.16 and found this to be true.
The file is created on the mounted s3 fs inside the container. When the container shuts down, the file is not saved on s3.

I am using the options:
--storage-config
and
--cloudmap

When I downgraded back to 0.2.13, it worked again.
Any ideas?

**Comment by danx0r** [comment]
fixed in recent versions
