### ISSUE TITLE
Add storage option and reasonable/big default

### ISSUE THREAD

**Issue by datahub-projects** [burstable-ai/burst#22]
* We don't currently have a way to specify the size of storage available on the ephemeral VM, and the default small instance is a little less than 8GB. I think we should add `--storage-type` and `--storage-size` options and default them to (for AWS) `st1` (throughput-optimized storage) and `100gb1`. The current cost of running a 100gb `st1` type EBS volume for 24 hours is $.15

@dan

**Comment by datahub-projects** [comment]
sort of duplicates #19

**Comment by danx0r** [comment]
obsolete
