### ISSUE TITLE
Overhaul config.yml

### ISSUE THREAD

**Issue by datahub-projects** [burstable-ai/burst#221]
CHANGE IN PLANS see comment below
* rm settings
* configurations --> services
* secret --> auth
* All providers:
  * rm _gpu_ options
  + gpu_enabled (true|false, for docker)
* EC2:
  + secret beneath auth
* GCP:
  + rm default_gpu
  + ex_accelerator_type
  + ex_accelerator_count

**Comment by genevievegraves** [comment]
Decided to leave settings and service as-is.
