### ISSUE TITLE
run pre-built docker images

### ISSUE THREAD

**Issue by datahub-projects** [burstable-ai/burst#223]
* ala Truera, Trilliam

**Comment by danx0r** [comment]
* note that burst use of docker is somewhat orthogonal to user using docker to run a task
* Dockerfile is same as usual (install needed pkgs)
* One package is docker client (docker for docker?)
* let's create a test example

**Comment by danx0r** [comment]
if a user wants to build their own docker image in their project, either their or our Dockerfile needs to be renamed and invoked

**Comment by danx0r** [comment]
commit 688da7899
