### ISSUE TITLE
Go through option flags and decide which ones to rename:

### ISSUE THREAD

**Issue by genevievegraves** [burstable-ai/burst#95]
*  --shutdown >> --stop
* --size
* --burst_user
* --sshuser
* etc.
* blocker for 0.2.18 release
*

**Comment by genevievegraves** [comment]
Kevin will go through this this week, by April 2.

**Comment by danx0r** [comment]
`--start` to restart stopped VM -- `--build` does this but having an explicit option may be clearer

**Comment by danx0r** [comment]
user BlakeSloan had what I consider to be an excellent suggestion: use the common cli paradigm of verb vs options.

Example:

```
burst list
burst build
burst run --verbosity 127 python3 mycode.py
and/or:
burst --verbosity 127 run python3 mycode.py
```

**Comment by danx0r** [comment]
Left out CLI overrides for storage for now

**Comment by danx0r** [comment]
https://docs.google.com/spreadsheets/d/1eMqbcMSP8qa0kDjzACqfbAnCthMcONScbuLwIlfBFrE/edit#gid=0
